# Generated by Django 3.2.5 on 2021-08-03 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210801_2222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['money_spent'], 'verbose_name': 'Покупатель', 'verbose_name_plural': 'Покупатели'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товар'},
        ),
        migrations.AlterModelOptions(
            name='purchasehistory',
            options={'verbose_name': 'Истрия Покупок', 'verbose_name_plural': 'Истрии Покупок'},
        ),
    ]
